### ISSUE TITLE
No module named 'torch._prims_common'

### ISSUE THREAD

**Issue by andrelindahl** [mickekring/ragnar#2]
Försöker köra appen men får ovanstående fel. Jag kör Windows. Någon tanke?

**Comment by andrelindahl** [comment]
Jag installerade om torch och nu verkar det funka. Den jobbar på med första transkriberingen. Tack för ett bra program!

**Comment by mickekring** [comment]
Tackar! Jag lägger till det i readme-filen lite senare, ifall fler råkar ut för samma sak.
